### ISSUE TITLE
Add support for Intercepting routes

### ISSUE THREAD

**Issue by svobik7** [svobik7/next-roots#92]
1. Add support for `(..)` intercepting routes syntax
2. Add parallel and intercepting routes example - article or author can be displayed even in modal
3. Update readme with parallel an interceptiong routes if needed

@see https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes

**Comment by svobik7** [comment]
Hi @Jon1VK, this is follow-up for your PR with parallel routes. My idea here is to support both parallel and intercepting routes and demonstrate it in example basically in the same way as https://github.com/vercel-labs/nextgram. Just pinging you if you wanna be part of this followup :-)

**Comment by Jon1VK** [comment]
In fact I was also yesterday thinking about the intercepting routes functionality and how it could be implemented quite similarly. I can help implementing this 😃 I have some free time at my hand this weekend so let's see if I can come up with a PR before monday.

**Comment by Jon1VK** [comment]
@svobik7, I have now two pull request, first one #93 implements the functionality and the second one #94 updates the example.

The Readme update is probably needed related the intercepting routes, since the intercepting route segment has to be translated also with i18n file, if the corresponding normal route has been also translated. You can check how I translated the segments in the example update PR.

**Comment by Jon1VK** [comment]
If the PR is approved as it is there will be one braking change: if you previously had a grouped route `/(auth)/login`, it will be changed in the `RouteName` type to be simply `/login`. As so if one previously called `router.getHref` with grouped form, it would be needed to be changed to the simple one.

**Comment by svobik7** [comment]
Published in 3.1.0
